### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by pySilver** [gavinwahl/django-optimistic-lock#6]
Hi,

Thanks for the code. Here is possible bug. 

```python
obj.save(updated_fields=['field_1', 'field_2'])
```

causes situation when data is saved but version is not bumped in db, but just in a ``obj`` instance. So next call to ``obj.save()`` will cause exception.  Of course that could be avoided by inclusing `version` field into updated_fields... but shouldn't it work out of the box?

**Comment by andybak** [comment]
This has just bitten me while extending Django's built in user model. This is in contrib.auth.models.py:

    def update_last_login(sender, user, **kwargs):
        user.last_login = timezone.now()
        user.save(update_fields=['last_login'])
    user_logged_in.connect(update_last_login)

So if I use OOL on my custom user model - it throws an concurrency error on login.

I guess I can work round this by disconnecting the signal and reconnecting my own that does include the version field in updated_fields

The only odd things is that the error only happens on the first login (the users are created from fixtures)

**Comment by gavinwahl** [comment]
@andybak does this sound like the steps to reproduce?:

- create a user from a fixture (what value of the version field is in the fixture?)
- trigger user_logged_in on the user

Is that it?

**Comment by pySilver** [comment]
You will always will have this kind of errors, once your traffic will grow. 
Few things to remember:

1. Probably you dont need to udpate last login more often than every hm minute (?)
2. Use db level lock
3. Offload this task to a background task (celery?)

```python
@app.task(bind=True)
@transaction.atomic
def set_last_login(self, user_id, last_login):
    """Updates user last-login datetime"""

    lock_id = '{0}-lock-{1}'.format(self.name, user_id)

    if acquire_lock(lock_id, self.request.id):
        try:
            user = get_user_model().objects.select_for_update().get(pk=user_id)
            user.last_login = last_login
            user.save(update_fields=['last_login'])
        finally:
            release_lock(lock_id)
    else:
        logger.info("Task {0} is locked. Is it already processing?".format(
            self.name
        ))
```

OOL will always fail if the same object updates too often (other threads will have outdated object most of the time)

**Comment by gavinwahl** [comment]
If update_fields bypassed versioning, the signal would always work. I think the desired behavior is to not update/check the version when it's not in update_fields

**Comment by andybak** [comment]
@pySilver - this is django core code - not mine.

**Comment by gavinwahl** [comment]
> OOL will always fail if the same object updates too often (other threads will have outdated object most of the time)

Isn't this the whole point of OOL? The failures are preventing you from overwriting the version from the other thread.

**Comment by andybak** [comment]
> @andybak does this sound like the steps to reproduce?

I'm struggling to pin it down. I've tried stuff like:

    s = Staff.objects.all()
    update_last_login('', s[10])

and it doesn't trigger the error - but logging in with the test client does:

    from django.test.client import Client
    c = Client()
    c.login(...)

Interestingly - it happens repeatedly this way. 

    c.login(...)
   [error]
    c.login(...)
   [error]
    c.login(...)
   [error]

And then it stops. Not after a certain number of repetitions - possibly after a fixed time period but I need to test further to make sure. 

I can post the traceback but I'm not sure how much it will help.

This is a custom user model but I don't have any customized save behaviour or signals beyond that provided by django and that added by ool...

**Comment by andybak** [comment]
OK. It's related to contrib.hashers.check_password wanting to update to the preferred algorithm.

So - a save can happen there, and then another save in update_last_login.

Personally - I can work around it for now by updating my fixtures so that the hashing algorithm doesn't need updating.

**Comment by pySilver** [comment]
> Isn't this the whole point of OOL? The failures are preventing you from overwriting the version from the other thread.

Thats true, but one should keep in mind where OOL might be used and where not. Objects that that are (or might be) updated very often (few times a second) should not use OOL or should implement custom failover logic such as "reload & reapply changes". Actually it's more business logic to decide what to do.

**Comment by gavinwahl** [comment]
@andybak , I think I can fix your bug by applying my patch above

**Comment by andybak** [comment]
@gavinwahl Thanks. Are you likely to merge that patch soon? If so - I'll just wait.

**Comment by gavinwahl** [comment]
@andybak yes, I will write a test and apply it tonight

**Comment by gavinwahl** [comment]
@andybak, I pushed this to the update-fields branch. Can you try that and see if it fixes your issue?

**Comment by andybak** [comment]
@gavinwahl - yes - that seems to have done the trick
