### ISSUE TITLE
Not seeing version field

### ISSUE THREAD

**Issue by gregpinero** [gavinwahl/django-optimistic-lock#9]
I change my model to look like this:

```
class MyModel(VersionedMixin, models.Model):
    version = VersionField()
```
But when I run python manage.py makemigrations, it says no changes detected.

And when I try to use the model it says "django.core.exceptions.ImproperlyConfigured: VersionedMixin models must have a VersionField"

**Comment by gavinwahl** [comment]
I'm not sure what's going on here. Are you able to reproduce this in a minimal project?

**Comment by gregpinero** [comment]
Sorry, turns out a had a method named "version"!  So the migration was ignoring the new field.
